[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pydmm-lib"
version = "0.0.2"
license = {text = "MIT"}
description = "Object model for standardising the structure of metadata applicable for mapping from one source data set to a target. Potentially being reshaped during the transfer."
keywords = ["data pipelines", "data", "pipelines", "metadata"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Database"
]
readme = "README.md"
# url='https://github.com/scott-diprose/pydmm-lib',
# authors = [
#     "Scott Diprose <scott.on.github.gmail.com>"
# ]
# python = "^3.8"
# packages=find_packages(include=('src'), exclude=('tests', 'docs')),
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
]
# dynamic = ["version"]

[project.optional-dependencies]
pdf = ["ReportLab>=1.2", "RXP"]
rest = ["docutils>=0.3", "pack ==1.1, ==1.3"]

[project.scripts]
my-script = "my_package.module:function"
