[project]
name = "pydtm-lib"
version = "0.0.2"
license = {text = "MIT"}
description = "Object model for standardising the structure of metadata applicable for mapping from one source data set to a target. Potentially being reshaped during the transfer."
keywords = ["data pipelines", "data", "pipelines", "metadata"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Database"
]
readme = "README.md"
# repository = "https://github.com/scott-diprose/pydtm-lib"
authors = [
    { name = "Scott Diprose", email = "scott.on.github@gmail.com" },
]
# python = "^3.8"
dependencies = [
    # "importlib-metadata; python_version<'3.8'",
    "pyyaml",
    # "lxml",
]
[project.optional-dependencies]
dev = [
    "yapf",
    "pylint",
    "pytest",
    "build",
    "twine",
    # "pre-commit",
    # "bump2version",
]
# dynamic = ["version"]


# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html


# Using packages disables the package auto-detection feature
# packages = [
#     { include = "pydtm-lib", from = "src" },
# #     { exclude = "tests" },
# #     { exclude = "docs" },
# ]


# [project.scripts]
# my-script = "pydtm.util:upgrade"



[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=45",
    "wheel",
    # "setuptools-scm>=6.2",
]


# [tool.setuptools.packages.find]
# where = ["src"]
# # include = ["pydtm*"]
# # exclude = ["pydtm.tests*"]



[tool.pylint.MASTER]
jobs = 1
[tool.pylint.STRING]
check-quote-consistency = "yes"
[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-module-docstring",
    "no-member",
]
# [tool.pylint.TYPECHECK]
# ignore-on-opaque-inference='yes'
